language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly
install:
  - utilities/travis/before-install.sh
script: utilities/phpunit.sh
after_script:
  - cat tests/logs/testdox.txt
  - cat tests/logs/logfile.tap
  - cat tests/logs/coverage.txt
